---
version: '2'
services:
  # Can't use service elasticsearch=<num> for now due to named volumes
  elasticsearch1:
  # Equivalent to:
  # docker run --rm --cap-add=IPC_LOCK --ulimit memlock=-1:-1 --ulimit nofile=65536:65536 -t -P --memory="4g" -e ES_JAVA_OPTS="-Xms2g -Xmx2g" -v esdata:/usr/share/elasticsearch/data elasticsearch:5.0.0-alpha5 bin/elasticsearch
    build:
      context: build/elasticsearch
      args:
        ELASTICSEARCH_VERSION: "${ELASTICSEARCH_VERSION}"
    cap_add:
      - IPC_LOCK
    command: supervisord -n -c /etc/supervisord.conf -l /data/supervisord/log/supervisord.log
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    image: "kent/elasticstack5:centos"
    mem_limit: 4g
    ports:
      - 9200:9200
      - 5601:5601
      - 9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /data:/data
volumes:
  esdata1:
    driver: local
